backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "string" }
      - { label: "Video", name: "video", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Tech Stack", name: "tech", widget: "list" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
